# -*- coding: utf-8 -*-
"""04_inference (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114hLhN_2LU1G2y3TyDti56C2iiVfsy3s
"""

from google.colab import drive
import sys
import torch

drive.mount('/content/drive')
sys.path.append(
"/content/drive/MyDrive/SupportAI"
)

from transformers import AutoModelForSequenceClassification, AutoTokenizer
import json

tokenizer = AutoTokenizer.from_pretrained("DeepPavlov/rubert-base-cased")

path = "/content/drive/MyDrive/SupportAI/models"
topic_model = AutoModelForSequenceClassification.from_pretrained(f"{path}/topic")
sentiment_model = AutoModelForSequenceClassification.from_pretrained(f"{path}/sentiment")
intent_model = AutoModelForSequenceClassification.from_pretrained(f"{path}/intent")

path1 = '/content/drive/MyDrive/SupportAI'
with open(f'{path1}/label_mappings.json', 'r') as f:
    label_mapping = json.load(f)

def predict(text, model, tokenizer):
    model.eval()

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=512
    )

    with torch.no_grad():
        logits = model(**inputs).logits

    probs = torch.softmax(logits, dim=1)

    pred_id = torch.argmax(probs, dim=1).item()
    confidence = probs[0, pred_id].item()

    return {
        "label": model.config.id2label[pred_id],
        "confidence": confidence
    }

def load_models(models_path):
    """
    Загружает токенизатор и все модели классификации.
    """

    tokenizer = AutoTokenizer.from_pretrained(
        "DeepPavlov/rubert-base-cased"
    )

    models = {
        "topic": AutoModelForSequenceClassification.from_pretrained(
            f"{models_path}/topic"
        ),
        "sentiment": AutoModelForSequenceClassification.from_pretrained(
            f"{models_path}/sentiment"
        ),
        "intent": AutoModelForSequenceClassification.from_pretrained(
            f"{models_path}/intent"
        ),
    }

    return tokenizer, models

def predict_all(text, models, tokenizer):
    results = {}

    for task, model in models.items():
        results[task] = predict(text, model, tokenizer)

    return results